apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "250m", memory: "256Mi" }
        ports:
        - containerPort: 80
